kubectl_version: "1.34.1-1.1"
kube_version_full: "1.34.1-1.1"
kube_version: "1.34"
pod_network_cidr: "10.244.0.0/16"
apiserver_ip: "192.168.56.10"

common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

kernel_modules:
  - overlay
  - br_netfilter